FROM node:16-alpine

WORKDIR /app

EXPOSE 8888

COPY package*.json ./

ENV PHANTOMJS_VERSION=2.1.1
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin
RUN apk update && apk add --no-cache fontconfig curl curl-dev && \
  cd /tmp && curl -Ls https://github.com/dustinblackman/phantomized/releases/download/${PHANTOMJS_VERSION}/dockerized-phantomjs.tar.gz | tar xz && \
  cp -R lib lib64 / && \
  cp -R usr/lib/x86_64-linux-gnu /usr/lib && \
  cp -R usr/share /usr/share && \
  cp -R etc/fonts /etc && \
  curl -k -Ls https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${PHANTOMJS_VERSION}-linux-x86_64.tar.bz2 | tar -jxf - && \
  cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs

COPY ./fonts/ArialRegular.ttf ./
RUN mkdir -p /usr/share/fonts/truetype/
RUN install -m644 ArialRegular.ttf /usr/share/fonts/truetype/
RUN rm ./ArialRegular.ttf

RUN npm install phantomjs-prebuilt --s
RUN npm install -g html-pdf
RUN npm install
RUN chmod -R a+rwx /srv

COPY . .

CMD ["npm", "run", "dev"]
